name: Boundary
favicon: null
layout_spectrum: 0.23022059327922761
typography_spectrum: 0.6563557717017829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.75
  lightness: 0.26193212484940886
  saturation: 0.12112035229802132
  rhythmicContrast: 0.097955517238006
purpose: []
